#' Calculate Quantiles
#' @param truevalues a tibble of featureRanks, feature names, feature weights, log feature weights and permutation # generated by the load_true_fws function
#' @param permutatedvalues a tibble of featureRanks, feature names, feature weights, log feature weights and permutation # generated by the load_permutated_fws function
#' @return A tibble of quantile data.
#' @export
calculateQuantiles<-function(truevalues,permutatedvalues){
  dm <- permutatedvalues %>% group_by(featureRank) %>%
  summarise(mean = mean(featureWeight),
            lower = quantile(featureWeight, prob=.025),
            upper = quantile(featureWeight, prob=.975)) %>%
            mutate(observed = truevalues$featureWeight) %>%
            mutate(logmean=log(mean)) %>%
            mutate(logupper=log(upper)) %>%
            mutate(loglower=log(lower)) %>%
            mutate(logobserved=log(observed))
  return(dm)
}


#' Calculate P value for entire feature set
#' @param permutatedvalues a tibble of featureRanks, feature names, feature weights, log feature weights and permutation # generated by the load_permutated_fws function
#' @param quantiledata a tibble containing: featureRanks, mean, lower, upper, and observed as well as logmean, loglower, logupper, logobserved generated by the calculateQuantiles function
#' @return A dataframe with one column and one row in which contains the proportion-based p-value for the entire feature set.
#' @export
calculatePvalueforSet<-function(permutatedvalues,quantiledata){
  d<-permutatedvalues
  numberofPermutations<-max(d$permutation)+1
  d <- d %>%
    mutate(Mean = rep( quantiledata$mean, times = numberofPermutations) ) %>%
    mutate(Dev = featureWeight - Mean)
  d <- d %>% mutate(Mean = rep( quantiledata$mean, times = numberofPermutations) ) %>% mutate(Dev = featureWeight - Mean)
  pi_permutated <- d %>% group_by(permutation) %>% summarise(Sum_abs_deviations = sum(abs(Dev)))
  pi_obs <- sum(abs(quantiledata$observed - quantiledata$mean))
# p-value for the pi statistic (sum of absolute deviations from rank mean weights)
  pvalpi<- (1 - mean(pi_permutated$Sum_abs_deviations < pi_obs))
  outdat<-data.frame("Proportion_based_P-value_for_entire_feature_set"=pvalpi)
  outdat
}

#' Calculate P value for each rank
#' @param truevalues a tibble of featureRanks, feature names, feature weights, log feature weights and permutation # generated by the load_true_fws function
#' @param permutatedvalues a tibble of featureRanks, feature names, feature weights, log feature weights and permutation # generated by the load_permutated_fws function
#' @param quantiledata a tibble containing: featureRanks, mean, lower, upper, and observed as well as logmean, loglower, logupper, logobserved generated by the calculateQuantiles function
#' @return A dataframe of featureRanks, proportions and pvalues
#' @export
calculatePvalueforRank<-function(truevalues,permutatedvalues,quantiledata){
  fweights <- aggregate(featureWeight~featureRank, permutatedvalues, 'c')
  fweights2 <- fweights %>% mutate(observedmean=truevalues$featureWeight)
  fweights3 <- fweights2 %>% mutate(proportion=rowSums(fweights2$featureWeight > fweights2$observedmean,na.rm = TRUE)) %>% mutate(pvalue=(proportion/100))
  fweightPvals <- fweights3[,c("featureRank","proportion","pvalue")]
  return(fweightPvals)

}


